"use client";
import {useEffect,useState} from "react";
import {allServices} from "@/data/services";
type Booking={id:string;name:string;phone:string;email:string;gotra:string;puja:string;preferredDate:string|null;city:string;message:string;status:string;createdAt:string};
type Data={items:Booking[];counts:Record<string,number>};
export default function AdminDashboard(){const [data,setData]=useState<Data|null>(null);const [query,setQuery]=useState("");const [statusFilter,setStatusFilter]=useState("");const [pujaFilter,setPujaFilter]=useState("");const [dateFilter,setDateFilter]=useState("");const [error,setError]=useState("");
 async function load(){try{const r=await fetch("/api/admin/bookings");const body=await r.json();if(!r.ok)throw new Error(body.error||"बुकिंग लोड नहीं हुई");setData(body);setError("")}catch(e){setError(e instanceof Error?e.message:"अनुरोध विफल")}}
 useEffect(()=>{let active=true;fetch("/api/admin/bookings").then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error||"बुकिंग लोड नहीं हुई");if(active)setData(body)}).catch(e=>{if(active)setError(e instanceof Error?e.message:"अनुरोध विफल")});return()=>{active=false}},[]);
 async function update(id:string,status:string){const r=await fetch("/api/admin/bookings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})});if(!r.ok){setError("स्थिति अपडेट नहीं हुई");return}await load()}
 const items=data?.items.filter(b=>`${b.name} ${b.phone} ${b.puja} ${b.city}`.toLowerCase().includes(query.toLowerCase())&&(!statusFilter||b.status===statusFilter)&&(!pujaFilter||b.puja===pujaFilter)&&(!dateFilter||(b.createdAt&&new Date(b.createdAt)>=new Date(`${dateFilter}T00:00:00`))))??[];
 const labels:Record<string,string>={total:"कुल बुकिंग",pending:"लंबित",confirmed:"पुष्ट",completed:"पूर्ण",rejected:"अस्वीकृत"};
 return <section className="section"><div className="container"><h1>बुकिंग डैशबोर्ड</h1>{error&&<p className="message" role="status">{error}</p>}{data&&<><div className="grid service-grid">{Object.entries(data.counts).map(([key,value])=><article className="card" key={key}><span>{labels[key]}</span><h2>{value}</h2></article>)}</div><div className="hero-actions"><input className="admin-search" aria-label="बुकिंग खोजें" placeholder="नाम, फोन या शहर खोजें" value={query} onChange={e=>setQuery(e.target.value)}/><select className="admin-search" aria-label="स्थिति से छाँटें" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">सभी स्थितियाँ</option><option value="pending">लंबित</option><option value="confirmed">पुष्ट</option><option value="completed">पूर्ण</option><option value="rejected">अस्वीकृत</option></select><select className="admin-search" aria-label="सेवा से छाँटें" value={pujaFilter} onChange={e=>setPujaFilter(e.target.value)}><option value="">सभी सेवाएँ</option>{allServices.map(s=><option key={s.slug} value={s.slug}>{s.title}</option>)}</select><label className="field">इस तारीख के बाद प्राप्त<input className="admin-search" type="date" value={dateFilter} onChange={e=>setDateFilter(e.target.value)}/></label></div><div style={{overflowX:"auto"}}><table className="admin-table"><thead><tr><th>नाम / फोन</th><th>सेवा</th><th>पसंदीदा तारीख</th><th>स्थिति</th><th>बुकिंग समय</th><th>विवरण</th></tr></thead><tbody>{items.map(b=><tr key={b.id}><td>{b.name}<br/><a href={`tel:${b.phone}`}>{b.phone}</a></td><td>{allServices.find(s=>s.slug===b.puja)?.title??b.puja}</td><td>{b.preferredDate||"—"}</td><td><select value={b.status} onChange={e=>void update(b.id,e.target.value)} aria-label={`${b.name} की स्थिति`}><option value="pending">लंबित</option><option value="confirmed">पुष्ट</option><option value="completed">पूर्ण</option><option value="rejected">अस्वीकृत</option></select></td><td>{new Date(b.createdAt).toLocaleDateString("hi-IN")}</td><td><details><summary>देखें</summary><p>ईमेल: {b.email||"—"}<br/>गोत्र: {b.gotra||"—"}<br/>शहर: {b.city||"—"}<br/>विशेष जानकारी: {b.message||"—"}</p></details></td></tr>)}</tbody></table>{items.length===0&&<p>इस चयन के लिए बुकिंग नहीं मिली।</p>}</div></>}</div></section>}
